name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ runner.home }}/android-sdk
      ANDROID_SDK_ROOT: ${{ runner.home }}/android-sdk
      PATH: ${{ runner.home }}/android-sdk/cmdline-tools/latest/bin:${{ runner.home }}/android-sdk/platform-tools:$PATH

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies and Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            git \
            zip \
            unzip \
            libffi-dev \
            libssl-dev \
            python3-dev \
            build-essential \
            autoconf automake libtool pkg-config
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Setup Android SDK cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          rm cmdline-tools.zip
          mv cmdline-tools latest

      - name: Accept Android licenses and install SDK packages
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393" "cmdline-tools;latest" "ndk-bundle" "platforms;android-21" "extras;android;m2repository" "extras;google;m2repository"

      - name: Run Buildozer build
        run: buildozer android debug
