name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            tar \
            openjdk-17-jdk \
            python3-pip \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libreadline-dev \
            libgdbm-dev \
            libbz2-dev \
            liblzma-dev \
            libxml2-dev \
            libxslt1-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libtiff5-dev \
            libmtdev-dev \
            xclip \
            xsel \
            libjpeg8-dev \
            python3-virtualenv \
            libtool \
            automake \
            autoconf \
            cmake \
            pkg-config \
            curl \
            libltdl-dev

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Initialize Buildozer Spec (if needed)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
