name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git build-essential
          pip install --upgrade cython buildozer

      - name: Copy existing buildozer.spec
        run: |
          cp buildozer.spec ./  # overwrite default if generated

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: subscription-app-debug-apk
          path: bin/*.apk
