name: Build Kivy APK

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROIDSDK: /usr/local/lib/android/sdk
      PATH: /usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            tar unzip zip curl openjdk-17-jdk build-essential python3-pip \
            libffi-dev libssl-dev libncurses5-dev libsqlite3-dev libpng-dev \
            libjpeg-dev libfreetype6-dev zlib1g-dev liblzma-dev \
            libgl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev autoconf automake cmake \
            xclip xsel libmtdev-dev pkg-config libtool

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Setup Android SDK cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          mv cmdline-tools latest
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0" "cmdline-tools;latest" "ndk;25.2.9519653"

      - name: Initialize buildozer.spec (if missing)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
