name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker container with Buildozer
        run: |
          docker run --rm -v ${{ github.workspace }}:/app \
          kivy/buildozer bash -c "
            cd /app &&
            pip install --upgrade pip cython wheel &&
            buildozer android debug
          "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LionsDenApp
          path: bin/*.apk
